#!/usr/bin/env bash
# World wide web


function domain_complete {
    IP1=$(dig "$i.$1" | grep -A1 'ANSWER SECTION:' | grep "$i.$1" | awk '{print $5}')
    R=$(dig "$i.$1" | grep -A1 'ANSWER SECTION:' | grep "$i.$1" | awk '{print $4}')
    echo "The subdomain $i is a $R record and points to $IP1"
}


if [ $# -eq 1 ]
    then
        for i in www lb-01 web-01 web-02
        do
            domain_complete "$1" "$i"
        done

elif [ $# -eq 2 ]
    then
        IP2=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep "$2.$1" | awk '{print $5}')
        R1=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep "$2.$1" | awk '{print $4}')
        echo "The subdomain $2 is a $R1 record and points to $IP2"
fi
