#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine.

sudo apt-get update
sudo apt-get install -y nginx

sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html                                                                  
