#!/usr/bin/env bash
# Instal HAproxy and setup load balancer

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y

sudo apt-get update
apt-get install haproxy=2.0.\* -y

sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo sed -i "$ a frontend my_server \n\t bind *:80 \n\t default_backend new \n\n backend new \n\t balance roundrobin \n\t server server1 35.231.133.57:80 check \n\t server server2 54.91.43.217:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
