#!/usr/bin/env bash
# Instal HAproxy and setup load balancer

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y

sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y

sudo chmod 777 /etc/haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo sed -i "$ a frontend my_server \n\tbind *:80 \n\tdefault_backend new \n\nbackend new \n\tbalance roundrobin \n\tserver server1 35.231.133.57:80 check \n\tserver server2 54.91.43.217:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
