#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

foldername=$(date +%d-%m-%y)
USER="root"

mysqldump -u $USER -p"$1" --all-databases > backup.sql

tar -cvzf "$foldername".tar.gz backup.sql