#!/usr/bin/env bash
# This script that displays bad luck for the 4th loop iteration ,displays good luck for the 8th loop iteration ,displays Holberton School for the other iterations

num=1
while [ $num -ne 11 ]
do
    if [ $num == 4 ]; then
        echo "bad luck"
    elif [ $num == 8 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    num=$(( num + 1 ))
done
