#!/usr/bin/env bash
# This script that displays numbers from 1 to 20.

num=1
while [ $num -ne 21 ]
do
    case $num in
        "4")   echo "$num"
        echo "bad luck from China"
        num=$(( num + 1 ));;
        "9") echo "$num"
        echo "bad luck from Japan"
        num=$(( num + 1 ));;
        "17") echo "$num"
        echo "bad luck from Italy"
        num=$(( num + 1 ));;
    esac
    echo "$num"
    num=$(( num + 1 ))
done
