#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

hours=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -ne 60 ]
    do
        echo "$minutes"
        minutes=$(( minutes + 1 ))
    done
    hours=$(( hours + 1 ))
done
